Merged bsconf into the configure script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,35 +1,499 @@
 #! /bin/sh
 #
-# This file is part of bsconf - a configure replacement.
-# Copyright (C) 2005 by Mike Sharov <msharov@users.sourceforge.net>
+# Copyright (C) 2008 by Mike Sharov <msharov@users.sourceforge.net>
 # This file is free software, distributed under the MIT License.
+#
+# This file is a replacement for autoconf configure, written due to the
+# enormous size of the latter and its slow performance. Autoconf runs a
+# whole suite of tests to determine each an every available feature. In
+# this script, the approach is to assume that Linux is the sane system,
+# and treat all others as braindead exceptions. Also, this configure is
+# assuming a more or less recent POSIX environment, eliminating many of
+# the legacy tests. For the point of view of the user, however, all the
+# functionality is identical to autoconf. For the developer, the change
+# is only in the way dependencies and substitutions are specified here.
+# The top sections are configuration, and are inteded to be seen as the
+# example of how to write them for your own project.
+#
+######################################################################
+#### Project Configuration ###########################################
+######################################################################
+
+PKG_NAME="ustl"
+PKG_MAJOR="1"
+PKG_MINOR="2"
+
+FILES="Config.mk config.h"
+
+PKG_BUGREPORT="Mike Sharov <msharov@users.sourceforge.net>"
+
+# Package options
+COMPONENTS="
+{
+name=[without-shared]
+desc=[Builds the shared library (if supported by the OS)]
+seds=[s/BUILD_SHARED\t= 1/#BUILD_SHARED\t= 1/]
+}{
+name=[with-static]
+desc=[	Builds the static library]
+seds=[s/#BUILD_STATIC\t= 1/BUILD_STATIC\t= 1/]
+}{
+name=[with-debug]
+desc=[	Compiles the library with debugging information]
+seds=[s/#DEBUG\t\t= 1/DEBUG\t\t= 1/]
+}{
+name=[without-bounds]
+desc=[Disable runtime bounds checking on stream reads/writes]
+seds=[s/#define WANT_STREAM_BOUNDS_CHECKING 1/#undef WANT_STREAM_BOUNDS_CHECKING/]
+}{
+name=[without-fastcopy]
+desc=[Disable specializations for copy/fill]
+seds=[s/#define WANT_UNROLLED_COPY 1/#undef WANT_UNROLLED_COPY/]
+}{
+name=[without-mmx]
+desc=[	Disable use of MMX/SSE/3dNow! instructions]
+seds=[s/#define WANT_MMX 1/#undef WANT_MMX/]
+}{
+name=[with-libstdc++]
+desc=[Link with libstdc++]
+seds=[s/#define WITHOUT_LIBSTDCPP 1/#undef WITHOUT_LIBSTDCPP/\n
+s/#NOLIBSTDCPP\t=/NOLIBSTDCPP\t=/]
+}";
+
+# Header files
+HEADERS="assert.h ctype.h errno.h fcntl.h float.h inttypes.h limits.h locale.h
+malloc.h alloca.h memory.h signal.h stdarg.h stddef.h stdint.h stdio.h
+stdlib.h string.h strings.h sys/stat.h sys/types.h sys/wait.h time.h
+unistd.h math.h stdlib.h";
+
+# Libraries
+LIBS="supc++ gcc_eh SystemStubs"
+
+# First pair is used if nothing matches
+PROGS="CC=gcc CC=cc CXX=g++ CXX=c++ DOXYGEN=doxygen
+LD=ld AR=ar RANLIB=ranlib RANLIB=touch INSTALL=install"
+
+# Environment variables
+ENVIRONS="CXXFLAGS LDFLAGS"
+
+# Automatic vars
+PKG_VERSTR="$PKG_MAJOR.$PKG_MINOR"
+PKG_STRING="$PKG_NAME $PKG_VERSTR"
+
+# Miscellaneous substitutions
+CUSTSUBS="s/@PACKAGE_NAME@/$PKG_NAME/g
+s/@PACKAGE_VERSION@/$PKG_VERSTR/g
+s/@PACKAGE_TARNAME@/$PKG_NAME/g
+s/@PACKAGE_STRING@/$PKG_STRING/g
+s/@PACKAGE_BUGREPORT@/$PKG_BUGREPORT/g
+s/@LIBNAME@/$PKG_NAME/g
+s/@LIB_MAJOR@/$PKG_MAJOR/g
+s/@LIB_MINOR@/$PKG_MINOR/g
+s/@LIB_BUILD@/0/g"
+
+######################################################################
+#### The rest of the file is configuration code. Leave it alone. #####
+######################################################################
+
+die() { rm -f config.sed config.cpu config.cpu.c; }
+
+#### Compile the configurator and generate initial config.sed ########
 
 if [ -z "$CC" ]; then
     for i in gcc g++ cc c++ c89 c99; do
-	CC=`which $i 2> /dev/null` && break;
-    done;
+	CC=`which $i 2> /dev/null` && break
+    done
 fi
-if [ -z "$CC" ]; then
-    echo "No C compiler found" && exit;
-fi
+[ -z "$CC" ] && "No C compiler found" && die
 
-PSTDDEF=`echo "#include <stddef.h>"|$CC -E -|grep stddef.h|head -n1|cut -d' ' -f3|cut -d\" -f2`
+# Determine gcc private directory
+PSTDDEF=`echo "#include <stddef.h>"|$CC -E -|grep stddef.h|head -n1|cut -d' ' -f3|cut -d'"' -f2`
 PINCDIR=`dirname $PSTDDEF`
 PLIBDIR=`dirname $PINCDIR`
-if [ -d $PLIBDIR/lib ]; then
-    PLIBDIR=$PLIBDIR/lib
-fi
-if [ ! -z "$PINCDIR" ]; then
-    PPATHS="$PPATHS --gccincludedir=$PINCDIR"
-fi
-if [ ! -z "$PLIBDIR" ]; then
-    PPATHS="$PPATHS --gcclibdir=$PLIBDIR"
-fi
-if [ ! -x bsconf -o bsconf.c -nt bsconf -o bsconf.h -nt bsconf ]; then
-    $CC -o bsconf bsconf.c
-fi
-if [ -x bsconf ]; then
-    ./bsconf $PPATHS $*;
+if [ -d $PLIBDIR/lib ]; then PLIBDIR=$PLIBDIR/lib; fi
+
+# Create and build the C configurator
+echo '#include <stdio.h>
+#include <sys/types.h>
+#include <sys/param.h>
+
+#if defined(__GNUC__) && (__i386__ || __x86_64) && !defined(__PIC__)
+static uint cpuid_supported (void)
+{
+    unsigned long forig, fnew;
+    asm ("pushf\n\tpop\t%0\n\t"
+	"mov\t%0, %1\n\txor\t$0x200000, %0\n\t"
+	"push\t%0\n\tpopf\n\tpushf\n\tpop\t%0"
+	: "=r"(fnew), "=r"(forig));
+    return (fnew != forig);
+}
+
+static uint cpuid (void)
+{
+    #define i_cpuid(a,r,c,d)	asm("cpuid":"=a"(r),"=c"(c),"=d"(d):"0"(a):"ebx")
+    const uint amdBits = 0xC9480000, extFeatures = 0x80000000, amdExtensions = 0x80000001;
+    uint r, c, d, caps;
+    if (!cpuid_supported()) return (0);
+    i_cpuid (0, r, c, d);
+    if (!r) return (0);
+    i_cpuid (1, r, c, d);
+    caps = (d & ~amdBits);
+    i_cpuid (extFeatures, r, c, d);
+    if (r != extFeatures) {
+	i_cpuid (amdExtensions, r, c, d);
+	caps |= d & amdBits;
+    }
+    return (caps);
+}
+#else
+static uint cpuid (void) { return (0); }
+#endif
+
+int main (void)
+{
+    typedef struct {
+	char	m_Bit;
+	char	m_Sub [55];
+    } SCpuCaps;
+    static const short int boCheck = 0x0001;
+    static const char boNames[2][16] = { "BIG", "LITTLE" };
+    static const SCpuCaps s_CpuCaps [] = {
+	{  0, "#undef CPU_HAS_FPU/#define CPU_HAS_FPU 1"		},
+	{  2, "#undef CPU_HAS_EXT_DEBUG/#define CPU_HAS_EXT_DEBUG 1"	},
+	{  4, "#undef CPU_HAS_TIMESTAMPC/#define CPU_HAS_TIMESTAMPC 1"	},
+	{  5, "#undef CPU_HAS_MSR/#define CPU_HAS_MSR 1"		},
+	{  8, "#undef CPU_HAS_CMPXCHG8/#define CPU_HAS_CMPXCHG8 1"	},
+	{  9, "#undef CPU_HAS_APIC/#define CPU_HAS_APIC 1"		},
+	{ 11, "#undef CPU_HAS_SYSCALL/#define CPU_HAS_SYSCALL 1"	},
+	{ 12, "#undef CPU_HAS_MTRR/#define CPU_HAS_MTRR 1"		},
+	{ 15, "#undef CPU_HAS_CMOV/#define CPU_HAS_CMOV 1"		},
+	{ 16, "#undef CPU_HAS_FCMOV/#define CPU_HAS_FCMOV 1"		},
+	{ 22, "#undef CPU_HAS_SSE /#define CPU_HAS_SSE 1"		},
+	{ 23, "#undef CPU_HAS_MMX/#define CPU_HAS_MMX 1"		},
+	{ 24, "#undef CPU_HAS_FXSAVE/#define CPU_HAS_FXSAVE 1"		},
+	{ 25, "#undef CPU_HAS_SSE /#define CPU_HAS_SSE 1"		},
+	{ 26, "#undef CPU_HAS_SSE2/#define CPU_HAS_SSE2 1"		},
+	{ 30, "#undef CPU_HAS_EXT_3DNOW/#define CPU_HAS_EXT_3DNOW 1"	},
+	{ 31, "#undef CPU_HAS_3DNOW/#define CPU_HAS_3DNOW 1"		}
+    };
+    uint i, caps;
+
+#if __GNUC__ >= 3
+    printf ("s/@INLINE_OPTS@/");
+    #if __GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
+	printf ("--param max-inline-insns-single=1024"
+		" \\\\\\n\\t\\t--param large-function-growth=65535"
+		" \\\\\\n\\t\\t--param inline-unit-growth=1024");
+    #else
+	printf ("-finline-limit=65535");
+    #endif
+    #if __GNUC__ >= 4
+	printf (" \\\\\\n\\t\\t-fvisibility-inlines-hidden"
+		" \\\\\\n\\t\\t-fno-threadsafe-statics -fno-enforce-eh-specs");
+    #endif
+    printf ("/g\n");
+#else
+    printf ("s/ \\?@INLINE_OPTS@//g\n"
+	"s/-Wredundant-decls/-Wno-redundant-decls/g\n");
+#endif
+#if __GNUC__ != 3
+    printf ("s/ \\?@libgcc_eh@//g\n");
+#endif
+#if __i386__
+    printf ("s/ \\?-fPIC//g\n");
+#endif
+#if defined(__GNUC__) || defined(__GLIBC_HAVE_LONG_LONG)
+    printf ("s/#undef HAVE_LONG_LONG/#define HAVE_LONG_LONG 1/g\n"
+	"s/#undef SIZE_OF_LONG_LONG/#define SIZE_OF_LONG_LONG %zd/g\n", sizeof(long long));
+#endif
+#if defined(__GNUC__) || (__WORDSIZE == 64) || defined(__ia64__)
+#ifndef BSD
+    printf ("s/#undef HAVE_INT64_T/#define HAVE_INT64_T 1/g\n");
+#endif
+#endif
+#ifndef __APPLE__
+    if (sizeof(size_t) == sizeof(unsigned long) && sizeof(size_t) != sizeof(uint))
+#endif
+	printf ("s/#undef SIZE_T_IS_LONG/#define SIZE_T_IS_LONG 1/g\n");
+#if __GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
+    printf ("s/#undef HAVE_VECTOR_EXTENSIONS/#define HAVE_VECTOR_EXTENSIONS 1/g\n");
+#else
+    printf ("s/ \\?-Wshadow//g\n");
+#endif
+    printf ("s/@BYTE_ORDER@/%s_ENDIAN/g\n"
+	"s/#undef RETSIGTYPE/#define RETSIGTYPE void/g\n"
+	"s/#undef const/\\/\\* #define const \\*\\//g\n"
+	"s/#undef inline/\\/\\* #define inline __inline \\*\\//g\n"
+	"s/#undef off_t/\\/\\* typedef long off_t; \\*\\//g\n"
+	"s/#undef size_t/\\/\\* typedef long size_t; \\*\\//g\n"
+	"s/#undef SIZE_OF_CHAR/#define SIZE_OF_CHAR %zd/g\n"
+	"s/#undef SIZE_OF_SHORT/#define SIZE_OF_SHORT %zd/g\n"
+	"s/#undef SIZE_OF_INT/#define SIZE_OF_INT %zd/g\n"
+	"s/#undef SIZE_OF_LONG/#define SIZE_OF_LONG %zd/g\n"
+	"s/#undef SIZE_OF_POINTER/#define SIZE_OF_POINTER %zd/g\n"
+	"s/#undef SIZE_OF_SIZE_T/#define SIZE_OF_SIZE_T %zd/g\n"
+	"s/#undef LSTAT_FOLLOWS_SLASHED_SYMLINK/#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1/g\n"
+	"s/#undef HAVE_STAT_EMPTY_STRING_BUG/\\/* #undef HAVE_STAT_EMPTY_STRING_BUG *\\//g\n",
+	boNames [(uint)(*((const char*)&boCheck))], sizeof(char),
+	sizeof(short), sizeof(int), sizeof(long), sizeof(void*), sizeof(size_t));
+
+    caps = cpuid();
+    for (i = 0; i < sizeof(s_CpuCaps)/sizeof(SCpuCaps); ++i)
+	if (caps & (1 << s_CpuCaps[i].m_Bit))
+	    printf ("s/%s/g\n", s_CpuCaps[i].m_Sub);
+#if __GNUC__ >= 3
+    printf ("s/ \\?@PROCESSOR_OPTS@/");
+    if (caps & (1 << 23))
+	printf (" -mmmx");
+    if (caps & ((1 << 22) | (1 << 25)))
+	printf (" -msse -mfpmath=sse");
+    if (caps & (1 << 26))
+	printf (" -msse2");
+    if (caps & ((1 << 30) | (1 << 31)))
+	printf (" -m3dnow");
+    printf ("/g\n");
+#else
+    printf ("s/ \\?@PROCESSOR_OPTS@//g\n");
+#endif
+    return (0);
+}' >config.cpu.c
+$CC -o config.cpu config.cpu.c
+[ ! -x config.cpu ] && echo "Configurator build failed" && die
+./config.cpu > config.sed
+
+#### Set host-dependent options ######################################
+
+SYSNAME=`uname|tr "[A-Z]" "[a-z]"`
+[ "`uname -m|tr '[A-Z]' '[a-z]'`" = "alpha" ] && SYSNAME="alpha"
+case "$SYSNAME" in
+    *solaris*| *sun*)	SYSNAME="sun";;
+    *darwin*| *osx*)	SYSNAME="mac";;
+    *alpha*)		SYSNAME="alpha";;
+    *bsd*)		SYSNAME="bsd";;
+    *)			SYSNAME="linux";;
+esac
+
+if [ "$SYSNAME" = "sun" ]; then
+    echo "s/-Wredundant-decls/-Wno-redundant-decls/g
+	s/@SHBLDFL@/-G/g" >>config.sed
 else
-    echo "Configurator build failed";
+    echo "s/#undef HAVE_THREE_CHAR_TYPES/#define HAVE_THREE_CHAR_TYPES 1/g" >>config.sed
 fi
+if [ "$SYSNAME" = "bsd" ]; then
+    echo "s/ \\?@libgcc_eh@//g
+	s/#define WITHOUT_LIBSTDCPP 1/#undef WITHOUT_LIBSTDCPP/g
+	s/NOLIBSTDCPP\\t= -nodefaultlibs /#NOLIBSTDCPP\\t= -nodefaultlibs/g
+	s/-Wredundant-decls/-Wno-redundant-decls/g
+	s/-Winline/-Wno-inline/g
+	s/#define HAVE_VA_COPY 1/#undef HAVE_VA_COPY/g" >>config.sed
+fi
+if [ "$SYSNAME" = "linux" -o "$SYSNAME" = "bsd" ]; then
+    echo "s/@SHBLDFL@/-shared -Wl,-soname=\$\{LIBSOLNK\}/g" >>config.sed
+elif [ "$SYSNAME" = "alpha" ]; then
+    echo "s/BUILD_SHARED\\t= 1 /#BUILD_SHARED\\t= 1/g
+	s/#BUILD_STATIC\\t= 1/BUILD_STATIC\\t= 1 /g" >>config.sed
+fi
+if [ "$SYSNAME" = "mac" ]; then
+    echo "s/ \\?@libgcc_eh@//g
+	s/@SYSWARNS@/-Wno-long-double/g
+	s/lib\$\{LIBNAME\}.so/lib\$\{LIBNAME\}.dylib/g
+	s/\$\{LIBSO\}.\$\{MAJOR\}.\$\{MINOR\}.\$\{BUILD\}/lib\$\{LIBNAME\}.\$\{MAJOR\}.\$\{MINOR\}.\$\{BUILD\}.dylib/g
+	s/\$\{LIBSO\}.\$\{MAJOR\}.\$\{MINOR\}/lib\$\{LIBNAME\}.\$\{MAJOR\}.\$\{MINOR\}.dylib/g
+	s/\$\{LIBSO\}.\$\{MAJOR\}/lib\$\{LIBNAME\}.\$\{MAJOR\}.dylib/g
+	s/@SHBLDFL@/-Wl,-single_module -compatibility_version 1 -current_version 1 -install_name \$\{LIBSOLNK\} -Wl,-Y,1455 -dynamiclib -mmacosx-version-min=10.4/g" >>config.sed
+else
+    echo "s/ \\?@SYSWARNS@//g" >>config.sed
+fi
+if [ "$SYSNAME" = "alpha" -o "$SYSNAME" = "mac" ]; then
+    echo "s/#undef SIZE_OF_BOOL/#define SIZE_OF_BOOL SIZE_OF_LONG/g" >>config.sed
+else
+    echo "s/#undef SIZE_OF_BOOL/#define SIZE_OF_BOOL SIZE_OF_CHAR/g" >>config.sed
+fi
+if [ "$SYSNAME" = "linux" ]; then
+    echo "s/#undef HAVE_RINTF/#define HAVE_RINTF 1/g" >>config.sed
+else
+    echo "s/ \\?-mfpmath=sse//g" >>config.sed
+fi
+if [ "$SYSNAME" = "mac" -o "$SYSNAME" = "bsd" ]; then
+    echo "s/#define HAVE_STRSIGNAL 1/#undef HAVE_STRSIGNAL/g" >>config.sed
+fi
+
+#### Printing helper functions #######################################
+
+PrintComponents() {
+    local cc=$COMPONENTS
+    echo "Options:"
+    while [ ! -z "$cc" ]; do
+	local name=`expr "$cc" : '[^}]*name=\[\([^]]*\)\]'`
+	local desc=`expr "$cc" : '[^}]*desc=\[\([^]]*\)\]'`
+	echo "  --$name	$desc"
+	cc=`expr "$cc" : '[^}]*}\(.*\)'`
+    done
+    echo
+}
+
+PrintHelp() {
+    echo "This program configures $PKG_STRING to adapt to many kinds of systems.
+
+Usage: configure [OPTION]...
+
+Configuration:
+  -h, --help		display this help and exit
+  -V, --version		display version information and exit
+
+Installation directories:
+  --prefix=PREFIX	architecture-independent files [/usr/local]
+  --exec-prefix=EPREFIX	architecture-dependent files [PREFIX]
+  --bindir=DIR		user executables [EPREFIX/bin]
+  --sbindir=DIR		system admin executables [EPREFIX/sbin]
+  --libexecdir=DIR	program executables [EPREFIX/libexec]
+  --datadir=DIR		read-only architecture-independent data [PREFIX/share]
+  --sysconfdir=DIR	read-only single-machine data [PREFIX/etc]
+  --sharedstatedir=DIR	modifiable architecture-independent data [PREFIX/com]
+  --localstatedir=DIR	modifiable single-machine data [PREFIX/var]
+  --libdir=DIR		object code libraries [EPREFIX/lib]
+  --includedir=DIR	C header files [PREFIX/include]
+  --oldincludedir=DIR	C header files for non-gcc [/usr/include]
+  --gccincludedir=DIR	GCC internal header files [PREFIX/include]
+  --infodir=DIR		info documentation [PREFIX/info]
+  --mandir=DIR		man documentation [PREFIX/man]
+
+System types:
+  --build=BUILD		configure for building on BUILD [guessed]
+  --host=HOST		cross-compile to build programs to run on HOST [BUILD]
+"
+    PrintComponents
+    echo "Report bugs to $PKG_BUGREPORT."
+}
+
+PrintVersion() {
+    echo "$PKG_NAME configure $PKG_VERSTR
+
+Copyright (c) 2003-2008, Mike Sharov <msharov@users.sourceforge.net>
+This configure script is free software under the MIT license.
+Unlimited permission to copy, distribute, and modify is granted."
+}
+
+SubVar() {
+    local esc2=`echo $2 | sed 's/\//\\\&/g'`
+    eval ac_var_$1='$esc2';
+    echo "s/@$1@/$esc2/g" >>config.sed
+}
+
+SubComp() {
+    local cc=$COMPONENTS
+    while [ ! -z "$cc" ]; do
+	local name=`expr "$cc" : '[^}]*name=\[\([^]]*\)\]'`
+	local seds=`expr "$cc" : '[^}]*seds=\[\([^]]*\)\]'`
+	[ "$name" = "$1" ] && echo -e $seds >>config.sed
+	cc=`expr "$cc" : '[^}]*}\(.*\)'`
+    done
+}
+
+for i in $*; do
+    case $i in
+	--)		break;;
+	--version |-V)	PrintVersion && die;;
+	--help |-h |-?)	PrintHelp && die;;
+	--*=*)		SubVar `expr "$i" : '--\([^=]*\)='` `expr "$i" : '[^=]*=\(.*\)'`;;
+	--*)		SubComp `expr "$i" : '--\(.*\)'`;;
+	*)		echo "Error: unrecognized option \"$i\"" && die;;
+    esac
+done
+
+#### Set directory prefixes ##########################################
+
+echo "s/@prefix@/${ac_var_prefix:=\/usr\/local}/g
+s/@exec_prefix@/${ac_var_exec_prefix:=$ac_var_prefix}/g
+s/@bindir@/$ac_var_exec_prefix\/bin/g
+s/@sbindir@/$ac_var_exec_prefix\/sbin/g
+s/@libexecdir@/$ac_var_exec_prefix\/libexec/g
+s/@datarootdir@/${ac_var_datarootdir:=$ac_var_prefix\/share}/g
+s/@datadir@/$ac_var_datarootdir/g
+s/@sysconfdir@/$ac_var_prefix\/etc/g
+s/@sharedstatedir@/$ac_var_prefix\/com/g
+s/@localstatedir@/$ac_var_prefix\/var/g
+s/@includedir@/${ac_var_includedir:=$ac_var_prefix\/include}/g
+s/@oldincludedir@/${ac_var_oldincludedir:=\/usr\/include}/g
+s/@docdir@/${ac_var_docdir:=$ac_var_datarootdir\/doc\/$PKG_NAME}/g
+s/@infodir@/$ac_var_datarootdir\/info/g
+s/@htmldir@/$ac_var_docdir/g
+s/@dvidir@/$ac_var_docdir/g
+s/@pdfdir@/$ac_var_docdir/g
+s/@psdir@/$ac_var_docdir/g
+s/@libdir@/${ac_var_libdir:=$ac_var_exec_prefix\/lib}/g
+s/@localedir@/$ac_var_datarootdir\/locale/g
+s/@mandir@/$ac_var_datarootdir\/man/g
+s/@gccincludedir@/${ac_var_gccincludedir:=`echo $PINCDIR | sed 's/\//\\\&/g'`}/g
+s/@gcclibdir@/${ac_var_gcclibdir:=`echo $PLIBDIR | sed 's/\//\\\&/g'`}/g
+s/@customincdir@/${ac_var_customincdir:=$ac_var_prefix\/include}/g
+s/@customlibdir@/${ac_var_customlibdir:=$ac_var_prefix\/lib}/g" >>config.sed
+
+if [ "$ac_var_prefix" != "\/usr\/local" -a "$ac_var_prefix" != "\/usr" ]; then
+    echo "s/ \?@CUSTOMINCDIR@/ -I$ac_var_customincdir/g
+s/ \?@CUSTOMLIBDIR@/ -L$ac_var_customlibdir/g" >>config.sed
+else
+    echo "s/ \?@CUSTOMINCDIR@//g
+s/ \?@CUSTOMLIBDIR@//g" >>config.sed
+fi
+
+#### Find headers, libs, programs, and subs ##########################
+
+SubHeadLibsProgs() {
+local INCPATH="$ac_var_oldincludedir $ac_var_includedir $ac_var_gccincludedir $ac_var_customincdir"
+INCPATH=`echo $INCPATH | sed 's/\\\\//g'`
+for i in $HEADERS; do
+    for p in $INCPATH; do
+	if [ -r "$p/$i" ]; then
+	    local hmacn=`echo $i | tr "a-z/.-" "A-Z___"`
+	    echo "s/#undef HAVE_$hmacn/#define HAVE_$hmacn 1/" >>config.sed
+	    break
+	fi
+    done
+done
+
+local LIBPATH="`echo $LD_LIBRARY_PATH | tr ':' ' '` $ac_var_libdir $ac_var_gcclibdir $ac_var_customlibdir /usr/lib /usr/local/lib /lib"
+LIBPATH=`echo $LIBPATH | sed 's/\\\\//g'`
+local LIBSUFFIX="so a la dylib"
+for i in $LIBS; do
+    local found=
+    for p in $LIBPATH; do
+	for s in $LIBSUFFIX; do
+	    if [ -r "$p/lib$i.$s" ]; then
+		found=" -l$i"
+		break
+	    fi
+	done
+	[ -z "$found" ] || break
+    done
+    echo "s/ \?@lib$i@/$found/g" >>config.sed
+done
+
+for i in $PROGS; do
+    local pname=`expr "$i" : '\([^=]*\)=[^=]*'`
+    local pcall=`expr "$i" : '[^=]*=\([^=]*\)'`
+    [ -x `which $pcall` ] && echo "s/@$pname@/$pcall/g" >>config.sed
+done
+# If nothing found in first loop, set the first pair anyway.
+for i in $PROGS; do
+    local pname=`expr "$i" : '\([^=]*\)=[^=]*'`
+    local pcall=`expr "$i" : '[^=]*=\([^=]*\)'`
+    echo "s/@$pname@/$pcall/g" >>config.sed
+done
+# And, finally, the environment variables
+for i in $ENVIRONS; do
+    local esci="`echo $i | sed 's/\//\\\&/g'`"
+    local esciv=`eval echo '"'\$\{$esci\}'"'`
+    [ ! -z "$esciv" ] && esciv=" $esciv"
+    echo "s/ \?@$i@/$esciv/g" >>config.sed
+done
+echo "$CUSTSUBS" >>config.sed
+}
+SubHeadLibsProgs
+
+#### Apply substitutions to all files ################################
+
+for i in $FILES; do
+    sed -f config.sed $i.in > $i
+done
+die
